name = "maud"
version = "1.0.0"
target = "erlang"
licenses = ["MIT"]
repository = { type = "github", user = "veeso", repo = "maud" }
description = "A MDX inspired Markdown renderer for Lustre and Gleam."

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = ">= 5.6.0 and < 6.0.0"
mork = ">= 1.11.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
